#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <cstdlib>
#include <ctime>
#include <vector>
#include <numeric>
#include <sstream>
#include <fstream>
#include <cstdlib>
#include <chrono>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::fixed;
using std::setprecision;
using std::string;
using std::copy;
using std::sort;
using std::srand;
using std::rand;
using std::time;
using std::vector;
using std::accumulate;
using std::stringstream;
using std::istringstream;
using std::ifstream;
using std::ofstream;
using std::move;